// Generated by gencpp from file jetsontx1_cvmodule/Peoplecount.msg
// DO NOT EDIT!


#ifndef JETSONTX1_CVMODULE_MESSAGE_PEOPLECOUNT_H
#define JETSONTX1_CVMODULE_MESSAGE_PEOPLECOUNT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jetsontx1_cvmodule
{
template <class ContainerAllocator>
struct Peoplecount_
{
  typedef Peoplecount_<ContainerAllocator> Type;

  Peoplecount_()
    : tot_detected_people(0)  {
    }
  Peoplecount_(const ContainerAllocator& _alloc)
    : tot_detected_people(0)  {
  (void)_alloc;
    }



   typedef int64_t _tot_detected_people_type;
  _tot_detected_people_type tot_detected_people;





  typedef boost::shared_ptr< ::jetsontx1_cvmodule::Peoplecount_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jetsontx1_cvmodule::Peoplecount_<ContainerAllocator> const> ConstPtr;

}; // struct Peoplecount_

typedef ::jetsontx1_cvmodule::Peoplecount_<std::allocator<void> > Peoplecount;

typedef boost::shared_ptr< ::jetsontx1_cvmodule::Peoplecount > PeoplecountPtr;
typedef boost::shared_ptr< ::jetsontx1_cvmodule::Peoplecount const> PeoplecountConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jetsontx1_cvmodule::Peoplecount_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jetsontx1_cvmodule::Peoplecount_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace jetsontx1_cvmodule

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'jetsontx1_cvmodule': ['/home/ubuntu/catkin_ws/src/jetsontx1_cvmodule/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::jetsontx1_cvmodule::Peoplecount_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jetsontx1_cvmodule::Peoplecount_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetsontx1_cvmodule::Peoplecount_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetsontx1_cvmodule::Peoplecount_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetsontx1_cvmodule::Peoplecount_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetsontx1_cvmodule::Peoplecount_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jetsontx1_cvmodule::Peoplecount_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71dd6017a25e8e7ae731854630c823b1";
  }

  static const char* value(const ::jetsontx1_cvmodule::Peoplecount_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71dd6017a25e8e7aULL;
  static const uint64_t static_value2 = 0xe731854630c823b1ULL;
};

template<class ContainerAllocator>
struct DataType< ::jetsontx1_cvmodule::Peoplecount_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetsontx1_cvmodule/Peoplecount";
  }

  static const char* value(const ::jetsontx1_cvmodule::Peoplecount_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jetsontx1_cvmodule::Peoplecount_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 tot_detected_people\n"
;
  }

  static const char* value(const ::jetsontx1_cvmodule::Peoplecount_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jetsontx1_cvmodule::Peoplecount_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tot_detected_people);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Peoplecount_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jetsontx1_cvmodule::Peoplecount_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jetsontx1_cvmodule::Peoplecount_<ContainerAllocator>& v)
  {
    s << indent << "tot_detected_people: ";
    Printer<int64_t>::stream(s, indent + "  ", v.tot_detected_people);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETSONTX1_CVMODULE_MESSAGE_PEOPLECOUNT_H
